### ISSUE TITLE
wrong formatting when using connect method

### ISSUE THREAD

**Issue by olajhidey** [Devon-White/SWML-python#1]
when I use the `connect ` method and I set the `from_number ` and the `to_number` it meant to  change when generating the script to **from** and **to** instead it's setting it as **from_number** and **to_number**

**Comment by andremartinssw** [comment]
I was _just_ running into this and about to open a ticket. Thanks @olajhidey

**Comment by Devon-White** [comment]
@olajhidey @andremartinssw Issue should be fixed in new version, give it a try :)

**Comment by olajhidey** [comment]
Will provide feedbacks, Thanks for looking into this swiftly

**Comment by olajhidey** [comment]
The fix worked perfectly well, Thank you!
