### ISSUE TITLE
Toggle Functions Throwing Incorrect Type

### ISSUE THREAD

**Issue by NoahConder** [Devon-White/SWML-python#5]
Within the SDK the Toggle functions function throws a warning for incorrect type when it only has a string. 
![image](https://github.com/Devon-White/SWML-python/assets/105017482/30f39a97-c6b1-47bd-ade6-621cc5d43ece)

![image](https://github.com/Devon-White/SWML-python/assets/105017482/f0aa0c94-4ced-4d88-9a57-7778a971d4d3)

Still works correctly, but creates some false errors and clutter.

**Comment by Devon-White** [comment]
Should be a union of a string or a array of strings

**Comment by Devon-White** [comment]
Fixed in latest version
